import { useEffect, useRef, type CSSProperties } from 'react'
export function Knob({label,value,min=0,max=1,step=.01,unit='',defaultValue=min,onChange}:{label:string;value:number;min?:number;max?:number;step?:number;unit?:string;defaultValue?:number;onChange(value:number):void}):React.JSX.Element{
  const host=useRef<HTMLDivElement>(null),current=useRef({value,onChange,min,max,step});current.current={value,onChange,min,max,step}
  const drag=useRef<{y:number;value:number}|null>(null)
  const change=(v:number):void=>{const c=current.current;if(Number.isFinite(v))c.onChange(Math.min(c.max,Math.max(c.min,Number((Math.round(v/c.step)*c.step).toFixed(5)))))}
  useEffect(()=>{const el=host.current;if(!el)return;const wheel=(e:WheelEvent):void=>{if(document.activeElement!==el)return;e.preventDefault();change(current.current.value+(e.deltaY<0?1:-1)*current.current.step*(e.shiftKey?1:5))};el.addEventListener('wheel',wheel,{passive:false});return()=>el.removeEventListener('wheel',wheel)},[])
  return <div className="marshall-control"><span>{label}</span><div ref={host} className="marshall-knob" role="slider" tabIndex={0} aria-label={label} aria-valuemin={min} aria-valuemax={max} aria-valuenow={value} aria-valuetext={`${value}${unit}`} title="拖动调整 · Shift 精调 · 双击复位" style={{'--rotation':`${-135+(value-min)/(max-min)*270}deg`} as CSSProperties}
    onDoubleClick={()=>change(defaultValue)} onPointerDown={e=>{e.currentTarget.focus();e.currentTarget.setPointerCapture(e.pointerId);drag.current={y:e.clientY,value}}} onPointerMove={e=>{if(drag.current)change(drag.current.value+(drag.current.y-e.clientY)*(max-min)/(e.shiftKey?1600:160))}} onPointerUp={()=>{drag.current=null}} onPointerCancel={()=>{drag.current=null}} onKeyDown={e=>{if(['ArrowUp','ArrowRight','ArrowDown','ArrowLeft','Home','End'].includes(e.key)){e.preventDefault();change(e.key==='Home'?min:e.key==='End'?max:value+(['ArrowUp','ArrowRight'].includes(e.key)?step:-step))}}}><i/></div><label className="knob-value"><input aria-label={`${label} 数值`} type="number" min={min} max={max} step={step} value={Number(value.toFixed(3))} onChange={e=>{if(e.target.value!=='')change(Number(e.target.value))}}/><span>{unit}</span></label></div>
}
