import { CLASSIC_AMPS, CLASSIC_CABS, CLASSIC_MODS, WHITEBOX_DEVICES, type EffectModule, type ToneAsset } from '@shared/arsenal.js'
import { Knob } from './Knob.js'
export function ModuleControls({ module, assets, onChange }: { module: EffectModule; assets: ToneAsset[]; onChange(module: EffectModule): void }): React.JSX.Element {
  const settings = module.settings, type = module.type
  const get = (path: string): unknown => path.split('.').reduce((v, key) => (v as Record<string, unknown>)[key], settings as unknown)
  const set = (path: string, value: unknown): void => { const next = structuredClone(module); const keys = path.split('.'); let obj = next.settings as unknown as Record<string, unknown>; for (const key of keys.slice(0, -1)) obj = obj[key] as Record<string, unknown>; obj[keys.at(-1)!] = value; onChange(next) }
  const select = (label: string, path: string, options: readonly { id: string; name: string }[]) => <label className="module-select">{label}<select aria-label={label} value={String(get(path) ?? '')} onChange={e => set(path, e.target.value || null)}>{options.map(o => <option key={o.id} value={o.id}>{o.name}</option>)}</select></label>
  const knob = (label: string, path: string, min = 0, max = 1, step = .01, unit = '') => <Knob key={path} label={label} value={Number(get(path))} min={min} max={max} step={step} unit={unit} onChange={v => set(path, v)} />
  const assetsFor = (kind: 'nam' | 'ir') => [{ id: '', name: '选择已导入资源' }, ...assets.filter(a => a.kind === kind).map(a => ({ id: a.id, name: a.name }))]
  return <div className="module-controls">
    {type === 'dynamic' && <>{select('动态类型', 'dynamic.device', [{id:'compressor',name:'Compressor 压缩'},{id:'boost',name:'Clean Boost'},{id:'gate',name:'Noise Gate'}])}<div className="module-knobs">{knob('Threshold','dynamic.threshold',-80,0,.5,' dB')}{knob('Ratio','dynamic.ratio',1,20,.1)}{knob('Attack','dynamic.attack',.1,100,.1,' ms')}{knob('Release','dynamic.release',10,1000,5,' ms')}{knob('Level','dynamic.gainDb',-60,24,.5,' dB')}</div></>}
    {type === 'drive' && <>{select('单块型号','drive.device',WHITEBOX_DEVICES)}<div className="module-knobs">{knob('Drive','drive.drive')}{!['microamp','distortion-plus','fuzzface'].includes(settings.drive.device) && knob('Tone','drive.tone')}{knob('Level','drive.level')}</div></>}
    {type === 'amp' && <>{select('箱头引擎','amp.engine',[{id:'classic',name:'经典箱头'},{id:'nam',name:'NAM 模型'}])}{settings.amp.engine === 'nam' ? select('NAM 音色','amp.assetId',assetsFor('nam')) : <>{select('箱头型号','amp.classic.device',CLASSIC_AMPS)}<div className="module-knobs">{(['gain','bass','middle','treble','master'] as const).map(k=>knob(k.toUpperCase(),`amp.classic.${k}`))}</div></>}</>}
    {type === 'cab' && <>{select('箱体引擎','cab.engine',[{id:'physical',name:'箱体模型'},{id:'ir',name:'脉冲响应 IR'}])}{settings.cab.engine === 'ir' ? select('箱体 IR','cab.assetId',assetsFor('ir')) : select('箱体型号','cab.physical.device',CLASSIC_CABS)}<div className="module-knobs">{knob('Low Cut','cab.lowCut',20,500,5,' Hz')}{knob('High Cut','cab.highCut',1000,20000,100,' Hz')}{knob('Level','cab.gainDb',-60,24,.5,' dB')}{settings.cab.engine === 'physical' && <>{knob('Volume','cab.physical.volumeLitres',10,300,1,' L')}{knob('Distance','cab.physical.distanceMetres',.25,3,.05,' m')}{knob('Angle','cab.physical.micAngle',0,75,1,'°')}</>}</div></>}
    {type === 'eq' && <><label className="module-select">频段<select aria-label="EQ 频段" value={settings.eq.bandCount} onChange={e=>set('eq.bandCount',Number(e.target.value))}><option value={5}>5 段</option><option value={7}>7 段</option></select></label><div className="module-knobs">{(settings.eq.bandCount===5?[80,240,750,2200,6600]:[100,200,400,800,1600,3200,6400]).map((hz,i)=>knob(`${hz} Hz`,`eq.bands.${i}`,-15,15,.5,' dB'))}{knob('Level','eq.gainDb',-60,24,.5,' dB')}</div></>}
    {type === 'mod' && <>{select('周边效果','mod.device',CLASSIC_MODS.filter(m=>m.id!=='ota-compressor'))}<div className="module-knobs">{knob('Rate','mod.rateHz',.05,10,.05,' Hz')}{knob('Depth','mod.depth')}{knob('Mix','mod.mix')}{knob('Feedback','mod.feedback',0,.85,.01)}{knob('Manual','mod.manual')}</div></>}
    {type === 'delay' && <>{select('延迟类型','delay.style',[{id:'digital',name:'Digital 数字延迟'},{id:'analog',name:'Analog 暗色延迟'},{id:'tape',name:'Tape 磁带回声'},{id:'reverse',name:'Reverse 反向延迟'}])}<div className="module-knobs">{knob('Time','delay.timeMs',1,2000,5,' ms')}{knob('Feedback','delay.feedback',0,.95,.01)}{knob('Tone','delay.tone',200,16000,100,' Hz')}{knob('Mix','delay.mix')}</div></>}
    {type === 'reverb' && <>{select('混响类型','reverb.style',[{id:'room',name:'Room'},{id:'hall',name:'Hall'},{id:'plate',name:'Plate'},{id:'spring',name:'Spring'}])}<div className="module-knobs">{knob('Decay','reverb.decay',.1,10,.1,' s')}{knob('Pre-delay','reverb.preDelayMs',0,200,1,' ms')}{knob('Damping','reverb.damping')}{knob('Mix','reverb.mix')}</div></>}
  </div>
}
