import { useRef } from 'react'
import { createEffectModule, type EffectModule, type ToneAsset } from '@shared/arsenal.js'
import { changeModuleParameter, effectDefinition, parameterValue } from '@shared/effect-catalog.js'
import { Select } from '../components/ui/Select.js'
import { Knob } from './Knob.js'
export function ModuleControls({module,assets,onChange}:{module:EffectModule;assets:ToneAsset[];onChange(module:EffectModule):void}):React.JSX.Element{
  const d=effectDefinition(module,assets),taps=useRef<number[]>([])
  const set=(path:string,value:unknown):void=>onChange(changeModuleParameter(module,path,value))
  const select=(c:typeof d.choices[number])=><label key={c.path} className="module-select">{c.label}<Select aria-label={c.label} value={String(parameterValue(module,c.path)??'')} onChange={e=>set(c.path,c.numeric?Number(e.target.value):e.target.value||null)}>{c.options.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</Select></label>
  const parameter=(p:typeof d.parameters[number])=><Knob key={p.path} label={p.label} value={Number(parameterValue(module,p.path))*p.scale} min={p.min*p.scale} max={p.max*p.scale} step={p.step*p.scale} unit={p.unit} defaultValue={Number(parameterValue(createEffectModule(module.type),p.path))*p.scale} onChange={v=>set(p.path,v/p.scale)}/>
  return <div className={`module-controls panel-${module.type}`}><div className="module-selects">{d.choices.filter(c=>!c.advanced).map(select)}
    {module.type==='delay'&&<><label className="module-check"><input type="checkbox" checked={module.settings.delay.sync} onChange={e=>set('delay.sync',e.target.checked)}/>节奏同步</label><button onClick={()=>{const now=performance.now();taps.current=[...taps.current.filter(t=>now-t<5000),now].slice(-5);if(taps.current.length>=2){const ms=(now-taps.current[0]!)/(taps.current.length-1);set(module.settings.delay.sync?'delay.bpm':'delay.timeMs',module.settings.delay.sync?Math.max(20,Math.min(400,Math.round(60000/ms))):Math.max(1,Math.min(2000,Math.round(ms))))}}}>Tap</button></>}
    {module.type==='cab'&&module.settings.cab.secondaryAssetId&&<label className="module-check"><input type="checkbox" checked={module.settings.cab.secondaryPolarity} onChange={e=>set('cab.secondaryPolarity',e.target.checked)}/>B 反相</label>}
  </div><div className="equipment-face"><span className="equipment-brand">BANDBUDDY <span>· {module.type.toUpperCase()}</span></span><h2>{d.name}</h2><div className="module-knobs">{d.parameters.filter(p=>!p.advanced).map(parameter)}</div></div>
  <details className="module-details"><summary>型号说明与高级参数</summary><p>{d.description}</p>{module.settings.dspRevision===1&&<p>此模块保留旧版声音算法。<button onClick={()=>onChange({...module,settings:{...module.settings,dspRevision:2}})}>升级算法</button></p>}<div className="module-selects">{d.choices.filter(c=>c.advanced).map(select)}</div><div className="module-knobs">{d.parameters.filter(p=>p.advanced).map(parameter)}</div>
  {module.type==='amp'&&module.settings.amp.engine==='nam'&&<><label className="module-check"><input type="checkbox" checked={module.settings.amp.calibration} onChange={e=>set('amp.calibration',e.target.checked)}/>按模型输入标定</label><label>声卡 0 dBFS 对应电平（dBu）<input type="number" min={-30} max={40} step={.1} value={module.settings.amp.inputDbU??''} onChange={e=>set('amp.inputDbU',e.target.value===''?null:Number(e.target.value))}/></label>{module.settings.amp.outputMode==='calibrated'&&<label>声卡输出 0 dBFS 对应电平（dBu）<input type="number" min={-30} max={40} step={.1} value={module.settings.amp.outputDbU??''} onChange={e=>set('amp.outputDbU',e.target.value===''?null:Number(e.target.value))}/></label>}<p>只在知道接口标定值时启用；缺少模型元数据时会提示，不自动猜测。</p></>}
  {module.type==='dynamic'&&module.settings.dynamic.device==='compressor'&&<label><input type="checkbox" checked={module.settings.dynamic.stereoLink} onChange={e=>set('dynamic.stereoLink',e.target.checked)}/>立体声联动</label>}
  </details></div>
}
