import { prepareNativeOutput, restoreBrowserOutput } from './output-coordinator.js'
import { create } from 'zustand'
import { chainModules, defaultEffectChain, type ArsenalDraft, type ArsenalMonitorState, type ArsenalPreset, type ArsenalState, type ArsenalWorkspace, type MonitorMode } from '@shared/arsenal.js'
import { factoryPresets } from '@shared/effect-catalog.js'
const initial=factoryPresets()[0]!
const idle:ArsenalMonitorState={active:false,mode:'off',sampleRate:0,bufferFrames:0,latencyMs:0,peak:[],outputPeak:0,xruns:0,error:null}
interface State {ready:boolean;draft:ArsenalDraft;library:ArsenalState;workspace:ArsenalWorkspace;monitor:ArsenalMonitorState;past:ArsenalDraft[];future:ArsenalDraft[];compare:ArsenalDraft|null;comparing:boolean;error:string;busy:boolean}
export const useArsenal=create<State>(()=>({ready:false,draft:{name:initial.name,presetId:initial.id,chain:initial.chain,selected:chainModules(initial.chain).find(m=>m.type==='amp')?.id,dirty:false},library:{presets:[],assets:[]},workspace:{draft:null,takes:[],quick:{recording:false,looping:false,durationMs:0}},monitor:idle,past:[],future:[],compare:null,comparing:false,error:'',busy:false}))
let started:Promise<void>|undefined,persistTimer:ReturnType<typeof setTimeout>|undefined,audioTimer:ReturnType<typeof setTimeout>|undefined,lastEdit=0
const fail=(e:unknown):void=>{useArsenal.setState({error:e instanceof Error?e.message:String(e)})}
export async function refreshLibrary():Promise<void>{useArsenal.setState({library:await window.bandbuddy.arsenal.list()})}
export function startArsenal():Promise<void>{if(started)return started;started=(async()=>{window.addEventListener('arsenal-output-error',event=>fail((event as CustomEvent).detail));const [library,workspace,monitor]=await Promise.all([window.bandbuddy.arsenal.list(),window.bandbuddy.arsenal.command({action:'workspace'}),window.bandbuddy.arsenal.monitorState()]);useArsenal.setState({ready:true,library,workspace,monitor,...(workspace.draft?{draft:workspace.draft}:{})});window.bandbuddy.arsenal.onMonitor(value=>{const old=useArsenal.getState().monitor;if(old.active!==value.active||old.mode!==value.mode||old.error!==value.error||old.tunerActive!==value.tunerActive)useArsenal.setState({monitor:value})})})().catch(e=>{started=undefined;fail(e)});return started}
function schedule():void{clearTimeout(persistTimer);persistTimer=setTimeout(()=>{void window.bandbuddy.arsenal.command({action:'draft',draft:useArsenal.getState().draft}).catch(fail)},250);clearTimeout(audioTimer);audioTimer=setTimeout(()=>{const {draft,monitor,busy}=useArsenal.getState();if(monitor.active&&!busy)void window.bandbuddy.arsenal.monitor({mode:monitor.mode,chain:draft.chain}).catch(fail)},100)}
export function editDraft(patch:Partial<ArsenalDraft>,coalesce=false):void{const s=useArsenal.getState(),now=Date.now(),group=coalesce&&now-lastEdit<400;useArsenal.setState({draft:{...s.draft,...patch,dirty:true},past:group?s.past:[...s.past,s.draft].slice(-80),future:[],comparing:false,error:''});lastEdit=coalesce?now:0;schedule()}
export function selectModule(selected:string):void{useArsenal.setState(s=>({draft:{...s.draft,selected}}));schedule()}
export function choosePreset(p:ArsenalPreset):void{const s=useArsenal.getState();useArsenal.setState({draft:{name:p.name,presetId:p.id,chain:{...p.chain,modules:chainModules(p.chain)},selected:chainModules(p.chain).find(m=>m.type==='amp')?.id??chainModules(p.chain)[0]?.id,dirty:false},past:[...s.past,s.draft].slice(-80),future:[],compare:null,comparing:false,error:''});schedule()}
export function newPreset():void{editDraft({name:'新预设',presetId:undefined,chain:{...defaultEffectChain(),modules:[]},selected:''})}
export function history(direction:'undo'|'redo'):void{const s=useArsenal.getState(),source=direction==='undo'?s.past:s.future,target=source.at(-1);if(!target)return;useArsenal.setState(direction==='undo'?{draft:target,past:s.past.slice(0,-1),future:[...s.future,s.draft],comparing:false}:{draft:target,future:s.future.slice(0,-1),past:[...s.past,s.draft],comparing:false});lastEdit=0;schedule()}
export function compareTone(capture=false):void{const s=useArsenal.getState();if(capture||!s.compare){useArsenal.setState({compare:structuredClone(s.draft),comparing:false});return}useArsenal.setState({draft:s.compare,compare:s.draft,comparing:!s.comparing});schedule()}
export async function setMonitor(mode:MonitorMode):Promise<void>{if(useArsenal.getState().busy)return;useArsenal.setState({busy:true,error:''});try{if(mode!=='off'&&!useArsenal.getState().monitor.active)await prepareNativeOutput();useArsenal.setState({monitor:await window.bandbuddy.arsenal.monitor({mode,chain:useArsenal.getState().draft.chain})})}catch(e){await restoreBrowserOutput().catch(()=>undefined);fail(e)}finally{useArsenal.setState({busy:false})}}
export async function saveTone(copy=false):Promise<void>{const draft=useArsenal.getState().draft,p=await window.bandbuddy.arsenal.savePreset({id:copy?undefined:draft.presetId,name:copy?`${draft.name.slice(0,95)} 副本`:draft.name,chain:draft.chain});if(useArsenal.getState().draft===draft)useArsenal.setState({draft:{...draft,presetId:p.id,name:p.name,dirty:false}});await refreshLibrary();schedule()}
export async function workspaceCommand(input:Parameters<typeof window.bandbuddy.arsenal.command>[0]):Promise<void>{useArsenal.setState({workspace:await window.bandbuddy.arsenal.command(input)});await refreshLibrary()}
/** Reset only when the renderer bridge is replaced (tests / a new app session). */
export function resetArsenalWorkspace():void{clearTimeout(persistTimer);clearTimeout(audioTimer);started=undefined;lastEdit=0;useArsenal.setState(useArsenal.getInitialState(),true)}
