import { useEffect, useRef, useState } from 'react'
import { Plus, Save, Trash2, ChevronLeft, ChevronRight, Upload, Search } from 'lucide-react'
import { chainModules, createEffectModule, defaultEffectChain, EFFECT_BLOCKS, type EffectBlock, type EffectChainSnapshot, type EffectModule, type ArsenalPreset, type ToneAsset, type MonitorMode } from '@shared/arsenal.js'
import { useRecordingSession, allowAudioAction } from '../recording-session.js'
import { DeviceFooter } from '../arsenal/DeviceFooter.js'
import { ModuleControls } from '../arsenal/ModuleControls.js'
import { Knob } from '../arsenal/Knob.js'
import './arsenal.css'
const labels: Record<EffectBlock,string> = {dynamic:'Dynamic',drive:'Drive',amp:'AMP',cab:'CAB',eq:'EQ',mod:'周边效果',delay:'Delay',reverb:'Reverb'}
const paths: Record<EffectBlock,string> = {dynamic:'M3 18V6h5l8 12h5M3 12h18',drive:'M3 16l5-8 4 8 4-8 5 8',amp:'M3 6h18v14H3zM6 9h12M7 15h.1M12 15h.1M17 15h.1',cab:'M4 3h16v18H4zM7 7h10v10H7zM9 9l6 6m0-6l-6 6',eq:'M6 3v18M12 3v18M18 3v18M3 8h6M9 15h6M15 6h6',mod:'M2 12c4-12 6-12 10 0s6 12 10 0',delay:'M3 12h3m2-5h3v10H8m6-13h3v16h-3m6-11h2v6h-2',reverb:'M3 16l4-8 4 8m2-10l2 12m2-15l2 18m2-12v6'}
function ModuleIcon({type}:{type:EffectBlock}):React.JSX.Element{return <svg viewBox="0 0 24 24" width="38" height="38" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[type]}/></svg>}
export function ArsenalPage({onToast}:{onToast(message:string):void}):React.JSX.Element {
  const [sidebarExpanded,setSidebarExpanded]=useState(true)
  const ownsMonitor=useRef(false)
  const [presets,setPresets]=useState<ArsenalPreset[]>([]),[assets,setAssets]=useState<ToneAsset[]>([])
  const [chain,setChain]=useState<EffectChainSnapshot>(()=>({...defaultEffectChain(),modules:[]})),[selected,setSelected]=useState('')
  const [presetId,setPresetId]=useState<string|undefined>(),[name,setName]=useState('新预设'),[query,setQuery]=useState('')
  const [monitor,setMonitor]=useState<MonitorMode>('off'),[busy,setBusy]=useState(false),[routing,setRouting]=useState(false),[dirty,setDirty]=useState(false)
  const recording=useRecordingSession(),latest=useRef(chain),mounted=useRef(true);latest.current=chain
  const modules=chainModules(chain), module=modules.find(m=>m.id===selected)
  const apply=(value:EffectChainSnapshot):void=>{if(!allowAudioAction())return;setChain(value);setDirty(true)}
  const choose=(p:ArsenalPreset):void=>{if(!allowAudioAction())return;setPresetId(p.id);setName(p.name);setChain({...p.chain,modules:chainModules(p.chain)});setSelected(chainModules(p.chain)[0]?.id??'');setDirty(false)}
  useEffect(()=>{mounted.current=true;void window.bandbuddy.arsenal.list().then(s=>{if(!mounted.current)return;setPresets(s.presets);setAssets(s.assets);if(s.presets[0])choose(s.presets[0])}).catch(e=>onToast(String(e)));const off=window.bandbuddy.arsenal.onMonitor(s=>{if(mounted.current){setMonitor(s.active?s.mode:'off');if(s.active)ownsMonitor.current=true}});return()=>{mounted.current=false;off();if(ownsMonitor.current)void window.bandbuddy.arsenal.monitor({mode:'off',chain:latest.current}).catch(()=>undefined)}},[])
  useEffect(()=>{if(monitor==='off'||routing||recording)return;const timer=setTimeout(()=>{void window.bandbuddy.arsenal.monitor({mode:monitor,chain}).catch(e=>{if(mounted.current)onToast(String(e))})},80);return()=>clearTimeout(timer)},[chain,monitor,routing,Boolean(recording)])
  const changeMonitor=async(mode:MonitorMode):Promise<void>=>{if(!allowAudioAction()||busy)return;ownsMonitor.current=mode!=='off'||ownsMonitor.current;setBusy(true);try{const s=await window.bandbuddy.arsenal.monitor({mode,chain:latest.current});if(mounted.current){setMonitor(s.active?s.mode:'off');if(s.active)ownsMonitor.current=true}}catch(e){onToast(String(e))}finally{if(mounted.current)setBusy(false)}}
  const save=async(copy=false):Promise<void>=>{if(!name.trim()){onToast('请填写预设名称');return}try{const p=await window.bandbuddy.arsenal.savePreset({id:copy?undefined:presetId,name:copy?`${name.trim()} 副本`:name.trim(),chain});setPresets(old=>[p,...old.filter(x=>x.id!==p.id)]);setPresetId(p.id);setName(p.name);setDirty(false);onToast('预设已保存')}catch(e){onToast(String(e))}}
  const updateModule=(next:EffectModule):void=>apply({...chain,modules:modules.map(m=>m.id===next.id?next:m)})
  const add=(type:EffectBlock):void=>{if(modules.length>=24){onToast('最多添加 24 个模块');return}const next=createEffectModule(type);apply({...chain,modules:[...modules,next]});setSelected(next.id)}
  const move=(direction:number):void=>{const index=modules.findIndex(m=>m.id===selected),next=index+direction;if(index<0||next<0||next>=modules.length)return;const list=[...modules];[list[index],list[next]]=[list[next]!,list[index]!];apply({...chain,modules:list})}
  const importAsset=async(kind:'nam'|'ir'):Promise<void>=>{try{const asset=await window.bandbuddy.arsenal.importAsset(kind);if(asset)setAssets((await window.bandbuddy.arsenal.list()).assets)}catch(e){onToast(String(e))}}
  return <main className={`arsenal-page modular-arsenal ${sidebarExpanded?'':'is-sidebar-collapsed'}`}><aside className="arsenal-sidebar" inert={!sidebarExpanded} aria-hidden={!sidebarExpanded}><div className="arsenal-sidebar-head"><h1>军火库</h1><button aria-label="收起预设" onClick={()=>setSidebarExpanded(false)}><ChevronLeft size={16}/></button></div><label className="arsenal-search"><Search size={16}/><input aria-label="搜索预设" placeholder="搜索预设…" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="arsenal-preset-list">{presets.filter(p=>p.name.toLowerCase().includes(query.toLowerCase())).map(p=><button key={p.id} className={`arsenal-preset ${presetId===p.id?'selected':''}`} onClick={()=>choose(p)}><span><b>{p.name}</b><small>{chainModules(p.chain).length} 个模块</small></span></button>)}</div><div className="arsenal-sidebar-actions"><button onClick={()=>{setPresetId(undefined);setName('新预设');apply({...defaultEffectChain(),modules:[]});setSelected('')}}><Plus size={16}/>新建预设</button><button disabled={!dirty} onClick={()=>void save()}><Save size={16}/>保存预设</button><button onClick={()=>void save(true)}>另存为副本</button></div></aside>
    <section className="arsenal-workspace"><header className="arsenal-toolbar">{!sidebarExpanded&&<button aria-label="展开预设" onClick={()=>setSidebarExpanded(true)}><ChevronRight size={16}/>预设</button>}<label className="preset-name">预设名称<input aria-label="预设名称" maxLength={120} value={name} onChange={e=>{setName(e.target.value);setDirty(true)}}/></label><div className="arsenal-toolbar-actions"><button onClick={()=>void importAsset('nam')}><Upload size={15}/>导入 NAM</button><button onClick={()=>void importAsset('ir')}><Upload size={15}/>导入 IR</button></div></header>
    <div className="modular-stage"><div className="module-chain"><span className="chain-terminal">INPUT</span>{modules.map((m,i)=><div className="module-step" key={m.id}><ChevronRight size={16}/><button className={`effect-card type-${m.type} ${m.id===selected?'selected':''} ${m.settings[m.type].enabled?'':'bypassed'}`} onClick={()=>setSelected(m.id)}><ModuleIcon type={m.type}/><b>{labels[m.type]}</b><small>{i+1} · {m.settings[m.type].enabled?'ON':'BYPASS'}</small></button></div>)}<ChevronRight size={16}/><span className="chain-terminal">OUTPUT</span></div><div className="module-add"><span>添加模块</span>{EFFECT_BLOCKS.map(type=><button key={type} onClick={()=>add(type)}><Plus size={13}/>{labels[type]}</button>)}</div></div>
    {module?<section className="arsenal-editor"><header className="editor-head"><label>模块类型<select aria-label="模块类型" value={module.type} onChange={e=>{const replacement=createEffectModule(e.target.value as EffectBlock);updateModule({...replacement,id:module.id})}}>{EFFECT_BLOCKS.map(t=><option key={t} value={t}>{labels[t]}</option>)}</select></label><div className="editor-actions"><button aria-label="模块前移" onClick={()=>move(-1)}><ChevronLeft/></button><button aria-label="模块后移" onClick={()=>move(1)}><ChevronRight/></button><button onClick={()=>updateModule({...module,settings:{...module.settings,[module.type]:{...module.settings[module.type],enabled:!module.settings[module.type].enabled}}})}>{module.settings[module.type].enabled?'旁通':'开启'}</button><button aria-label="删除模块" onClick={()=>{apply({...chain,modules:modules.filter(m=>m.id!==module.id)});setSelected('')}}><Trash2 size={16}/></button></div></header><ModuleControls module={module} assets={assets} onChange={updateModule}/></section>:<div className="module-empty">添加或选择模块，调整你的声音。</div>}
    <div className="rack-levels"><Knob label="Input" value={chain.inputGainDb} min={-60} max={24} step={.5} unit=" dB" onChange={inputGainDb=>apply({...chain,inputGainDb})}/><Knob label="Output" value={chain.outputGainDb} min={-60} max={24} step={.5} unit=" dB" onChange={outputGainDb=>apply({...chain,outputGainDb})}/></div>
    <DeviceFooter monitor={monitor} busy={busy||routing||Boolean(recording)} getChain={()=>latest.current} onMonitor={mode=>void changeMonitor(mode)} onRouting={setRouting} onToast={onToast}/></section></main>
}
