export const IPC = {
  libraryList: 'library:list',
  libraryGet: 'library:get',
  libraryChooseSource: 'library:choose-source',
  libraryChooseStems: 'library:choose-stems',
  libraryImportSource: 'library:import-source',
  libraryImportStems: 'library:import-stems',
  libraryUpdate: 'library:update',
  libraryDelete: 'library:delete',
  libraryOpenLocation: 'library:open-location',
  libraryReseparate: 'library:re-separate',
  practiceSave: 'practice:save',
  tasksList: 'tasks:list',
  tasksCancel: 'tasks:cancel',
  tasksRetry: 'tasks:retry',
  tasksClear: 'tasks:clear',
  runtimeGet: 'runtime:get',
  runtimeDetect: 'runtime:detect',
  runtimeInstall: 'runtime:install',
  runtimeCancel: 'runtime:cancel',
  runtimeRepair: 'runtime:repair',
  runtimeRemove: 'runtime:remove',
  runtimeClearModel: 'runtime:clear-model',
  settingsGet: 'settings:get',
  settingsChooseDataRoot: 'settings:choose-data-root',
  settingsUpdate: 'settings:update',
  mediaCapabilities: 'media:capabilities',
  mediaDetectBpm: 'media:detect-bpm',
  exportStart: 'export:start',
  exportChoosePath: 'export:choose-path',
  windowMinimize: 'window:minimize',
  windowToggleMaximize: 'window:toggle-maximize',
  windowClose: 'window:close',
  eventLibraryChanged: 'event:library-changed',
  eventTasksChanged: 'event:tasks-changed',
  eventRuntimeChanged: 'event:runtime-changed',
  eventSettingsChanged: 'event:settings-changed',
  eventMediaChanged: 'event:media-changed',
  eventWindowHidden: 'event:window-hidden'
} as const

export type IpcChannel = (typeof IPC)[keyof typeof IPC]
